---
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: Update & Install Packages
          command: |
            apt-get update && apt-get dist-upgrade
            apt-get install wget
      - run:
          name: Download & install binary
          command: |
            wget https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz
            tar -xvf PHP_Linux-x86_64.tar.gz
      - checkout
      - run:
          name: Lint sources
          command: |
            ./tests/lint.sh -p bin/php7/bin/php -d ./src/jacknoordhuis/discordrelay
      - run:
          name: Build plugin phar
          command: |
            bin/php7/bin/php ./build.php
      - store_artifacts:
          path: DiscordRelay.phar
          destination: DiscordRelay.phar
...