###  Discord-Relay v0.0.1-dev#1 configuration file  ###
general:
  # The default channel messages are relayed to and from discord.
  # Will respect both relay-from-discord and relay-to-discord flags (can be set to only relay one way.)
  default-channel: general
  bot:
    token: your-bot-token-here
  channels:
    - name: general
      discord-id: channel ID
      options:
        relay-from-discord: true
        relay-to-discord: true
    - name: log
      discord-id: channel ID
      options:
        relay-console: true